#!/bin/bash -euf

brew -v >/dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle

sleep 5;

# Oh-My-ZSH!
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Symlink dotfiles
ln -s .zshrc "$HOME/.zshrc"
ln -s .vimrc "$HOME/.vimrc"
ln -s .tmux.conf "$HOME/.tmux.conf"

git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# AWS
#pip install awscli

# nvm
#curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
