cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'jq'
brew 'nvm'
brew 'packer'
brew 'plantuml'
brew 'python'
brew 'terraform'
brew 'direnv'
cask 'google-chrome'
cask 'google-drive'
cask 'atom'
cask 'iterm2'
