cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'jq'
brew 'nvm'
brew 'plantuml'
brew 'python'
brew 'terraform'
brew 'direnv'
brew 'vim'
brew 'tmux'
brew 'reattach-to-user-namespace'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'docker'
cask 'etcher'
